### PR TITLE
Overrides getAttributesForInsert & getDirtyForUpdate instead of performInsert & performUpdate to 

### LINKED ISSUE #87: Geometry fields are passed as Expression during Eloquent model event are fired.
Hi!

During the insert, the library operate in three steps:
1. It caches all the original geometries attributes as their defined type (a point as Point, and so on...) and convert all geometries as Expression.
2. It performs insert using the eloquent `performInsert` method
3. It refills the model attributes as their original states

https://github.com/clickbar/laravel-magellan/blob/main/src/Database/Eloquent/HasPostgisColumns.php#L116-L118

The problem here is that if you use the laravel eloquent model event:
```php
class Person
{
    use \Clickbar\Magellan\Database\Eloquent\HasPostgisColumns;

    /** @var string[] */
    protected $postgisColumns = [
        'location' => [
            'type' => 'geometry',
            'srid' => 4326
        ]
    ];
    
    protected $dispatchesEvents = [
        'created' => \App\Events\Person\Created::class
    ];
}
```
The event is dispatched from the eloquent `performInsert` call, meaning it's called with all the geometries attributes as `Expression` and not as `Point`.

I'll investigate if there is some kind of hook inside the Eloquent model event dispatcher to see if this could be fixed properly.

### PR DESCRIPTION
**Pull request by RomainMazB**
This fix #87 by decreasing the code override from the Eloquent Model class.
- Instead of overriding the whole `performInsert` method, we now override the `getAttributesForInsert` method which only cares about getting the attributes to be inserted into the database.
- Instead of overriding the whole `performUpdate` method, we now override the `getDirtyForUpdate` method which only cares about getting the modified attributes to be updated into the database.

### CODE REVIEW

**Comment by saibotk** [comment]
Wow, thank you very very much for the quick response on this!
Also this looks very good and much better. 

Can we maybe add a simple test case to prevent regressions in the future? Something like a quick model event test?
Also a small entry in the changelog would be nice. 


Thank you so much!

**Comment by saibotk** [comment]
I just saw, we do not have a proper eloquent test ready, so see this as optional if it is too much for now, we will do it later anyway.

**Comment by RomainMazB** [comment]
I'll write a test to avoid future regression, it's not a problem.

Probably during the weekend or on Monday.

**Comment by RomainMazB** [comment]
Just re-thinking about it.

Adding database tests means that github actions will now need to run postgres + postgis to valid the tests.

I am not familiar with github actions so I can't provide a PR on that. What do you recommend?

**Comment by saibotk** [comment]
Dont worry i can add those later thank you 🙏

**Review by saibotk — APPROVED** [review]
Sorry for taking so long! Was really swamped in the last weeks.

Just checked the code and this looks very good!
It is a much cleaner solution and both methods fit perfectly for our use case!

Note: I might add tests later on, but that depends on how we will implement this in v2, where we might switch to casters anyway.

Thank you so much for looking into this! We really really appreciate the effort!

**Comment by saibotk** [comment]
Oh @RomainMazB, can you quickly run `composer fix` and add an entry to the `CHANGELOG.md` about this fix?

If not i can also do that :)

**Review by djfhe — APPROVED** [review]
LGTM!

**Comment by maximepvrt** [comment]
@saibotk can you release this fix ?

**Comment by saibotk** [comment]
done @maximepvrt sry should have done that sooner!

**Pull request merged**
