### PR TITLE
ci: Adjust permissions, Add changelog enforcer, Remove unused, Fix -> Check Styling

### PR DESCRIPTION
**Pull request by saibotk**
Refactor Styling Workflow to not commit changes anymore, since we use PRs anyways and want to allow the developer to decide on when to run pint.
This otherwise only annoys developers, when working on drafts etc.
And it also breaks for people without write permissions.

Additionally this PR changes the following:

- Removed dependabot auto-merge (unused, rather we want to manually merge them)
- Removed changelog update workflow (unused, we update the Changelog with every PR)
- Added changelog enforcer workflow (so we do not forget to update the Changelog in PRs)
- Adjusted all workflows to use minimal permissions
- Lock dependencies to ensure idempotency in tests / ci
- Fix current ci / lint issues

### CODE REVIEW

**Review by studnitz — COMMENTED** [review]
Looks good, but I'm not sure about committing the `composer.lock` file because of PHPStan and Pint. I would instead pin the version of PHPStan and Pint, similarly how you pin the version of Prettier.

**Comment by saibotk** [comment]
I locked it because of all dependencies which might introduce changes. Is there any concern with the committed lock file? Eg. in JS ecosystem it is the go to way and having a reproducible setup is very important.

**Comment by studnitz** [comment]
Committing the lock file is not the norm for any PHP packages that I know of, so I'm skeptical about that being the solution. And it introduces the need for manually updating the dependencies, which is more work but can be also seen as more correct.

**Comment by saibotk** [comment]
Yes, that is also what made me skeptical at first, but as i found the answer on the composer page and did not find any other reason for not committing the lock file, i think it brings more value to update the packages manually and not have breaking changes (when hard coding pint / phpstan, we would also need to manually upgrade those anyways).

So do you think of this as a blocker or would this be fine for now?

**Review by studnitz — APPROVED** [review]

**Pull request merged**
