### PR TITLE
chore: Laravel 11 support

### PR DESCRIPTION
**Pull request by faytekin**

### CODE REVIEW

**Comment by bykof** [comment]
LGTM

**Review by bykof — APPROVED** [review]

**Review by bykof — APPROVED** [review]

**Review by bykof — APPROVED** [review]

**Comment by faytekin** [comment]
> Hey 👋 thanks for your work, i've just updated the dependencies in other PRs so pint etc does not clutter this PR.
> 
> Would you be able to rebase your changes on the latest main branch?
> 
> Otherwise, I can take over.
> 
> Thank you very much ✌️



@saibotk Done 🚀

**Comment by saibotk** [comment]
Perfect, looks good. Can you just add some phpstan ignores to the docrine type calls? Then we are good to go 💅

**Comment by faytekin** [comment]
Sure thing! Just added the PHPStan ignores for the Doctrine type calls as suggested. Ready to merge whenever you are! 😊🚀

**Review by saibotk — APPROVED** [review]

**Comment by faytekin** [comment]
@saibotk Just wanted to check on the Laravel 11 support pull request. It’s merged for a couple of days now. Can we expect a release soon? Thanks! 👍🚀

**Pull request merged**
